version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
      POSTGRES_DB: blog
    ports:
      - 5432:5432